### ISSUE TITLE
Kubernetes secrets management

### ISSUE THREAD

**Issue by The-smooth-operator** [mozilla-iam/iam-infra#132]
Currently Kubernetes secrets are not version controlled and managed manually.
As we are moving the cluster to a more production ready state, this issue has to be tackled. Let's keep the discussion about possible solutions in this thread.

**Comment by The-smooth-operator** [comment]
I have been looking at [Blackbox](https://github.com/StackExchange/blackbox) developed by StackExchange.
Basically it is a CLI tool that uses GPG for encrypting selected files. Seems to be simple and intuitive to use and it fits our needs.

I'm interested in knowing what do you think about it, from your perspective as a developer, administrator, security eng...
@fiji-flo @ziegeer @andrewkrug @danielhartnell

**Comment by ziegeer** [comment]
I was leaning toward [Credstash](https://github.com/fugue/credstash) as I like the security of the KMS backend but I'm not sure what the development story is for that so other's experiences will be more important.

Things like transparent `git diff` concern me as far as leaking secrets.

**Comment by gdestuynder** [comment]
just as a note: we replaced credstash by directly using parameter store in AWS for CIS

**Comment by The-smooth-operator** [comment]
IT-SRE has decided to use private git repos + git-crypt to store secrets. However this decision might be revisited in the future.
For the moment I've created a new private repo, added all the GPG keys of the IT-SRE team members, and encrypted the few secrets we have.
Calling this one done

**Comment by gdestuynder** [comment]
Another note: we're probably going to replace parameter store by aws secrets now that its a thing, mainly because of threshold/rate limits. Note that it helps you directly, but in case someone read this issue someday :)

**Comment by The-smooth-operator** [comment]
@gdestuynder thanks for your input. We were also thinking about using AWS secrets, and most likely we will revisit this in few months. I'll come back to you for guidance ;)
