### ISSUE TITLE
Use CoreDNS in the production cluster

### ISSUE THREAD

**Issue by The-smooth-operator** [mozilla-iam/iam-infra#141]
EKS was using by default kube-dns for having name resolution services in the cluster.
After release 1.11 they have replaced kube-dns in favor of coreDNS, because is more customizable.
For the moment we don't need to use any specific feature of CoreDNS however we want to use it in order to standarize our clusters and use the supported standards.

It should be fast and easy to do, but can also create problems. More information on how to do it here https://docs.aws.amazon.com/eks/latest/userguide/coredns.html

**Comment by The-smooth-operator** [comment]
Past week we upgraded to CoreDNS on the stage cluster.
It was very smooth, and so far we haven't experience any issues. An upgrade for prod is plan for next Thursday

**Comment by The-smooth-operator** [comment]
We did the upgrade in prod. It was again very smooth, we didn't experience downtime or problems. 
At the moment the deployment of kube-dns is left with 0 replicas. If all is fine, tomorrow we will clean it up and close this issue.

**Comment by ziegeer** [comment]
We removed the old unused scaled-down kube-dns deployment, servicecaccount and configmap.  This is all done now.
