### ISSUE TITLE
Graylog behind Auth0

### ISSUE THREAD

**Issue by The-smooth-operator** [mozilla-iam/iam-infra#153]
Graylog has to be exposed to the internet to make it easier for developers to see the logs of their application. 
We're going to deploy an [OIDC proxy](https://github.com/mozilla-iam/mozilla.oidc.accessproxy) in front of it, which will take care of Authenticating users.

**Comment by The-smooth-operator** [comment]
@ziegeer currently Graylog is exposed behind an OIDC proxy. While the setup might be not 100% perfect, I'm happy with it.
Can we call this one done?

**Comment by ziegeer** [comment]
I'd rather not call it done yet.  It may be a while before I can get back
to this due to other priorities, but I want to see it through if I can.

**Comment by ziegeer** [comment]
We got this ironed out last week and this is all working nicely now!
