### ISSUE TITLE
set resource constraints on Mozillians pods

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-iam/iam-infra#23]
Best practice to avoid a pod consuming more resources than anticipated.

**Comment by The-smooth-operator** [comment]
Mozillians won't run in our clusters anymore, we are going with DinoPark instead.
However this ticket is still valid, and DinoPark objects are setting theirwe resource quota in all the projects.
Furthermore we plan to set up a quota per Namespace. Doing that we can ensure that even if some developer deploys objects without a quota, those are still implemented preventing an application using all the resources from the cluster.
