### ISSUE TITLE
create a Grafana dashboard for Mozillians

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-iam/iam-infra#24]
We can probably just start with the default metrics that a Django Prometheus exporter once that's implemented.

**Comment by The-smooth-operator** [comment]
I'll be happy to help in setting up this dashboard once Mozillians is deployed.

**Comment by The-smooth-operator** [comment]
Mozillians doesn't exist anymore.
I'm helping Florian, Andrew and Khang in the creation of Grafana dashboards for visualizing the metrics of their applications. Closing this task as we deprecated Mozillians
