### ISSUE TITLE
move the EKS Terraform module into a separate repository

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-iam/iam-infra#36]
It's funny, the module was the reason I initially created this repository. I do want to keep the Terraform in here to create and destroy clusters.

https://github.com/mozilla-iam/eks-deployment/blob/master/infrastructure/main.tf

I want to move the module itself into a separate repository so I can develop and test the module without having to push changes to this repository. In the `main.tf` above, I would pin a tagged version of the remote module and issue new releases here when we need to upgrade the module.

**Comment by The-smooth-operator** [comment]
@danielhartnell is this one still relevant?
