### ISSUE TITLE
Configure Grafana datasource for displaying CloudWatch metrics

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-iam/iam-infra#60]
I would like to make sure we're collecting metrics for the new external resources we are depending on now (RDS, Elasticache, etc.).

https://github.com/prometheus/cloudwatch_exporter

**Comment by danielhartnell** [comment]
I spoke with Alberto and we could also use CloudWatch as a data source in Grafana. I only intend on grabbing metrics for a few services - primarily RDS. I like the simplicity with the secondary data source and I'd recommend that unless we have a good reason to push everything into Prometheus.

**Comment by The-smooth-operator** [comment]
I've been working on PR-117 to add Cloudwatch as a Grafana datasource. Once it's merged and deployed (Terraform and Kubenertes) I'll work on the dashboards.

However I see a downside of not having the metrics in Prometheus, and that's how to do alerting. We could alert from Grafana itself, but I think is better having a single source of truth for defining alerts: Prometheus.
I'm interested in knowing your opinion about that. Even if we decide to scrape all the metrics from Prometheus, I think having that PR merged and playing with Cloudwatch+Grafana is fun.

**Comment by The-smooth-operator** [comment]
At this point, we have exporters fetching data from all the desired AWS managed services, and there's no need to give Grafana permissions for talking to Cloudwatch.
Performing this is not a big deal, so we could revisit it if necessary.
